### ISSUE TITLE
Utilise systemd to isolate minio

### ISSUE THREAD

**Issue by SISheogorath** [truenas/minio#7]
Currently the minio service runs a python script, which calls sudo, that overall is really not great in regards of system isolation.

Given that TrueNAS Scale is using Linux under the hood, I would propose to utilise systemd's capabilities to isolate services and running them as non-root from the beginning.

An basic example can be found upstream: https://github.com/minio/minio-service/blob/24bc1684943aad86eab70a31b1df4350cf16156f/linux-systemd/minio.service

But there is further room for improvements, easiest assessed by running `systemd-analyze security minio.service` on your TrueNAS Scale setup.

If there is interest in these improvements, I would be willing to contribute.

Alternatively one could consider to put minio in a container and not talk about it again 😅 Either way is fine and at the end of the day, uses the same kernel features. Just the current way, is a bit "YOLOed".

**Comment by william-gr** [comment]
We use Jira o keep track of all TrueNAS issues.https://ixsystems.atlassian.net/jira/software/c/projects/NAS/issues

I do believe we have a ticket/request for this but no work has been done yet. Contributions are always welcomed. Thank you!

**Comment by SISheogorath** [comment]
For completeness, link to the (new) upstream issue: https://ixsystems.atlassian.net/browse/NAS-118162
